const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      isFavourite: false,
      isCompared: false,
      category: 'chair',
      price: 30,
      oldPrice: 40,          // z WDP250801-6
      promoPrice: 25,        // z master
      stars: 2,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_1.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      isFavourite: true,
      isCompared: false,
      category: 'chair',
      price: 30,
      oldPrice: 35,          // z WDP250801-6
      promoPrice: 25,        // z master
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_2.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      isFavourite: false,
      isCompared: true,
      category: 'chair',
      price: 30,
      oldPrice: 37,          // z WDP250801-6
      promoPrice: 25,        // z master
      stars: 2,
      userStars: 5,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_3.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      isFavourite: true,
      isCompared: true,
      category: 'chair',
      price: 30,
      oldPrice: 42,          // z WDP250801-6
      promoPrice: 25,        // z master
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_4.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'chair',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_5.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },

    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      category: 'sofa',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/sofa_aenean_ru_bristique_6.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      category: 'sofa',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/sofa_aenean_ru_bristique_7.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      category: 'sofa',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/sofa_aenean_ru_bristique_8.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      category: 'sofa',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/sofa_aenean_ru_bristique_9.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      category: 'sofa',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/sofa_aenean_ru_bristique_10.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },

    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      category: 'bed',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/bed_aenean_ru_bristique_11.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      category: 'bed',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/bed_aenean_ru_bristique_12.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      category: 'bed',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/bed_aenean_ru_bristique_13.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      category: 'bed',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/bed_aenean_ru_bristique_14.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      category: 'bed',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 1,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/bed_aenean_ru_bristique_15.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },

    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      category: 'table',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/table_aenean_ru_bristique_16.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      category: 'table',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 5,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/table_aenean_ru_bristique_17.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      category: 'table',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/table_aenean_ru_bristique_18.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      category: 'table',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 2,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/table_aenean_ru_bristique_19.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      category: 'table',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/table_aenean_ru_bristique_20.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },

    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      category: 'dining',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/dining_aenean_ru_bristique_21.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      category: 'dining',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/dining_aenean_ru_bristique_22.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      category: 'dining',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/dining_aenean_ru_bristique_23.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      category: 'dining',
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/dining_aenean_ru_bristique_24.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
  ],
  cart: {
    products: [],
  },
  feedback: [
    {
      id: '1',
      name: 'John Doe',
      description: 'Homeowner',
      comment:
        'The service was exceptional and the quality of the products exceeded my expectations. Every piece of furniture fits perfectly in my home and adds a touch of elegance. I highly recommend this company to anyone looking for premium furniture.',
      image: '/images/feedback/john_doe.jpg',
    },
    {
      id: '2',
      name: 'Mike Smith',
      description: 'Designer',
      comment:
        'I am truly impressed by the unique furniture designs and the attention to detail. The pieces are both stylish and comfortable, making my studio a more creative and inviting space. I will definitely purchase more items in the future.',
      image: '/images/feedback/mike_smith.jpg',
    },
    {
      id: '3',
      name: 'Alice Johnson',
      description: 'Interior Decorator',
      comment:
        'This is the best place for modern furniture! The selection is fantastic and the quality is outstanding. My clients are always pleased with the results, and I appreciate the excellent customer support throughout the entire process.',
      image: '/images/feedback/alice_johnson.jpg',
    },
  ],
  viewport: {
    width: 1024,
    mode: 'desktop',
  },
};

export default initialState;
