const initialState = {
  promotion: {
    leftBox: {
      label_1: 'Guest Room',
      label_2: 'Sofa',
      discount: '-20%',
      img: '/images/products/dining_aenean_ru_bristique_24.jpg',
    },
    topBox: {
      label_1_1: 'Office ',
      label_1_2: 'chair',
      label_2: 'Collection',
      price: '$200.00',
      img1: '/images/products/chair_aenean_ru_bristique_2.jpg',
      img2: '/images/products/chair_aenean_ru_bristique_1.jpg',
    },
    bottomBox: {
      label_1_1: 'Special ',
      label_1_2: 'collection',
      label_2: 'Save up 45% of furniture',
      img: '/images/products/sofa_aenean_ru_bristique_6.jpg',
    },
  },
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  marketingTags: [
    { id: 'featured', name: 'Featured' },
    { id: 'topSeller', name: 'Top Seller' },
    { id: 'saleOff', name: 'Sale off' },
    { id: 'topRated', name: 'Top Rated' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      isFavourite: false,
      isCompared: false,
      category: 'bed',
      marketingTags: ['featured'],
      price: 30,
      oldPrice: 40,
      promoPrice: 25,
      stars: 2,
      userStars: 3,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_1.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      isFavourite: true,
      isCompared: false,
      category: 'bed',
      marketingTags: ['featured'],
      price: 30,
      oldPrice: 35,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_2.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      isFavourite: false,
      isCompared: true,
      category: 'bed',
      marketingTags: ['saleOff'],
      price: 30,
      oldPrice: 37,
      promoPrice: 25,
      stars: 2,
      userStars: 5,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_3.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      isFavourite: true,
      isCompared: true,
      category: 'bed',
      marketingTags: ['topRated'],
      price: 30,
      oldPrice: 42,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_4.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      category: 'bed',
      marketingTags: ['topSeller'],
      price: 30,
      promoPrice: 25,
      stars: 2,
      userStars: 0,
      promo: 'sale',
      newFurniture: true,
      availability: 'in stock',
      image: '/images/products/chair_aenean_ru_bristique_5.jpg',
      overview: {
        quick: 'this is quick overview',
        full: 'this is full overview',
      },
    },
    // pozostałe produkty analogicznie – zachowując marketingTags i promoPrice z master, kategorię master
  ],
  cart: { products: [] },
  feedback: [
    {
      id: '1',
      name: 'John Doe',
      description: 'Homeowner',
      comment:
        'The service was exceptional and the quality of the products exceeded my expectations. Every piece of furniture fits perfectly in my home and adds a touch of elegance. I highly recommend this company to anyone looking for premium furniture.',
      image: '/images/feedback/john_doe.jpg',
    },
    {
      id: '2',
      name: 'Mike Smith',
      description: 'Designer',
      comment:
        'I am truly impressed by the unique furniture designs and the attention to detail. The pieces are both stylish and comfortable, making my studio a more creative and inviting space. I will definitely purchase more items in the future.',
      image: '/images/feedback/mike_smith.jpg',
    },
    {
      id: '3',
      name: 'Alice Johnson',
      description: 'Interior Decorator',
      comment:
        'This is the best place for modern furniture! The selection is fantastic and the quality is outstanding. My clients are always pleased with the results, and I appreciate the excellent customer support throughout the entire process.',
      image: '/images/feedback/alice_johnson.jpg',
    },
  ],
  viewport: { width: 1024, mode: 'desktop' },
  quickView: { open: false, productId: null },
  brands: [
    { id: 1, name: 'IKEA', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 2, name: 'Leroy Merlin', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 3, name: 'Home & You', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 4, name: 'Agata', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 5, name: 'Black Red White', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 6, name: 'Black Red White', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 7, name: 'Black Red White', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 8, name: 'Black Red White', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 9, name: 'Black Red White', logo: 'https://i.imgur.com/z8BGkzc.png' },
    { id: 10, name: 'Black Red White', logo: 'https://i.imgur.com/z8BGkzc.png' },
  ],
};

export default initialState;
